= How to Build a High Performance Autonomous Mapping Drone From Scratch!!!

Whether used by farmers to monitor the health of their crops, environmental researchers to collect water temperature data or even archaeologists to view soil patterns from the air, unmanned aerial platforms are gradually becoming essential civilian research tools.  Even so, for the vast majority of people around the world, autonomous aerial vehicles represent either scary military killing machines, or expensive toys for rich people. While citizen-scientists, grassroots researchers, humanitarian activists etc…​ have grown to recognize the enormous potential of having access to such technology, the dominant perception is still that it can only be acheived at singnificant expense. After-all, simple economic logic dictates that technological capability is directly proportional to monetary investment (in other words 'you get what you pay for').  It would seem a reasonable expectation then, that a flying robot capable of autonomously navigating a precise flight plan while deploying an assortnment of 3D mapping cameras and sensors, would require significant monetary investment.  Indeed, models like the impressive https://store.3drobotics.com/products/x8-m?taxon_id=32&_ga=1.11959028.133431665.1440776780[X8-M] or the https://www.store.3drobotics.com/products/aero-m?taxon_id=32&_ga=1.181327591.133431665.1440776780[Aero-M] by 3DRobotics have been specially designed for the emerging aerial mapping market and can be up and flying for roughly $5500.



consumerhin the growing user-community of UAV hobbyists, it has long been established that even the most expensive model available on the consumer market can easily be outmatched for very little money using a combination of open source software, open source hardware and "Do-It-Yourself" techniques. 

