= How to Build a High Performance Autonomous Mapping Drone From Scratch!!!

Whether used by farmers to monitor the health of their crops, environmental researchers to collect water temperature data or even archaeologists to view soil patterns from the air, unmanned aerial platforms are gradually becoming essential civilian research tools.  Even so, for the vast majority of people around the world, autonomous aerial vehicles represent either scary military killing machines, or expensive toys for rich people. While citizen-scientists, grassroots researchers, humanitarian activists etc…​ have grown to recognize the enormous potential of having access to such technology, the dominant perception is still that it can only be acheived at singnificant expense. After-all, simple economic logic dictates that technological capability is directly proportional to monetary investment (in other words 'you get what you pay for').  It would seem a reasonable expectation then, that a flying robot capable of autonomously navigating a precise flight plan while deploying an assortnment of 3D mapping cameras and sensors, would require significant monetary investment.  Indeed, models like the impressive https://store.3drobotics.com/products/x8-m?taxon_id=32&_ga=1.11959028.133431665.1440776780[X8-M] or the https://www.store.3drobotics.com/products/aero-m?taxon_id=32&_ga=1.181327591.133431665.1440776780[Aero-M] by 3DRobotics have been specially designed for the emerging aerial mapping market and can be up and flying for roughly $5500.  While this is barely a fraction of what a military vehicle would cost (even one of comparable size and capability) the price tag is still far beyond the range of most students, researchers, citizen scientists etc...  

This is where the story would normally end in most cases, but thanks to a unique process of open source development, it is very much possible to have an aerial mapping vehicle with comparable (or better) capabilities than the models mentioned above for less than $200!!!  More than that, it should be possible to build almost the entire aircraft out of relatively common, off-the-shelf components and free (as in "beer") software!   





